services:
  node:
    build: ./config/telegram-bot
    container_name: node_streaming
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./config/telegram-bot:/app
      - ./media:/app/downloads

  web:
    image: nginx:latest
    container_name: nginx_streaming
    working_dir: /usr/share/nginx/html
    restart: unless-stopped
    volumes:
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/html:/usr/share/nginx/html:ro
      - ./media/video:/usr/share/nginx/html/media/video:ro
    networks:
      - proxy-network
      - default

  icecast:
    image: libretime/icecast
    container_name: icecast_streaming
    restart: unless-stopped
    volumes:
      - ./config/icecast/icecast.xml:/etc/icecast.xml:ro
      - ./config/icecast/logs/error.log:/usr/local/icecast/logs/error.log
      - ./config/icecast/logs/access.log:/usr/local/icecast/logs/access.log

  ices2:
    build: ./config/ices2
    container_name: ices2_streaming
    restart: unless-stopped
    depends_on:
      - icecast
    volumes:
      - ./config/ices2/ices-playlist.xml:/etc/ices2/ices-playlist.xml:ro
      - ./media/audio:/audio:ro

networks:
  proxy-network:
    external: true