services:
  node:
    build:
      context: ./config/telegram-bot
    container_name: node_streaming
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./config/telegram-bot:/app
      - ./media:/app/downloads
    command: ["node", "bot.js"]
    networks:
      - app_network

  web:
    image: nginx:latest
    container_name: nginx_streaming
    working_dir: /usr/share/nginx/html
    restart: unless-stopped
    volumes:
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/html:/usr/share/nginx/html
      - ./media/video:/usr/share/nginx/html/media/video
    networks:
      - app_network
      - proxy-network

  icecast:
    image: libretime/icecast
    container_name: icecast_streaming
    restart: unless-stopped
    volumes:
      - ./config/icecast/icecast.xml:/etc/icecast.xml
      - ./config/icecast/logs/error.log:/usr/local/icecast/logs/error.log
      - ./config/icecast/logs/access.log:/usr/local/icecast/logs/access.log
    networks:
      - app_network

  ices2:
    build:
      context: ./config/ices2
    container_name: ices2_streaming
    restart: unless-stopped
    depends_on:
      - icecast_streaming
    volumes:
      - ./config/ices2/ices-playlist.xml:/etc/ices2/ices-playlist.xml
      - ./media/audio:/audio
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
  proxy-network:
    external: true