services:
  node:
    build:
      context: telegram-bot
    container_name: node
    working_dir: /app
    volumes:
      - ./telegram-bot:/app
      - ./nginx/hls:/app/downloads
    command: ["node", "server.js"]
    ports:
      - "5000:5000"
    networks:
      - app_network

  web:
    image: nginx:latest
    container_name: web
    working_dir: /usr/share/nginx/html
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/hls:/usr/share/nginx/html/hls
      - ./telegram-bot/downloads:/usr/share/nginx/html/downloads
    networks:
      - app_network

  icecast:
    image: moul/icecast
    container_name: icecast
    ports:
      - "8000:8000"
    volumes:
      - ./icecast/icecast.xml:/etc/icecast.xml
    networks:
      - app_network

  ices2:
    build:
      context: ./ices2
    container_name: ices2
    depends_on:
      - icecast
    volumes:
      - ./ices2/ices-playlist.xml:/etc/ices2/ices-playlist.xml
      - ./nginx/hls:/home/alumno/canciones
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
