services:
  node:
    build:
      context: telegram-bot
    container_name: node
    working_dir: /app
    volumes:
      - ./telegram-bot:/app
      - ./nginx/hls:/app/downloads
    command: ["node", "bot.js"]
    ports:
      - "5000:5000"
    networks:
      - app_network

  web:
    image: nginx:latest
    container_name: nginx_streaming
    working_dir: /usr/share/nginx/html
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/hls:/usr/share/nginx/html/video/hls
      - ./telegram-bot/downloads:/usr/share/nginx/html/downloads
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - app_network
      - proxy-network

  icecast:
    image: libretime/icecast
    container_name: icecast
    ports:
      - "8000:8000"
    volumes:
      - ./icecast/icecast.xml:/etc/icecast.xml
      - ./logs/error.log:/usr/local/icecast/logs/error.log
      - ./logs/access.log:/usr/local/icecast/logs/access.log
    networks:
      - app_network
      - proxy-network

  ices2:
    build:
      context: ./ices2
    container_name: ices2
    depends_on:
      - icecast
    volumes:
      - ./ices2/ices-playlist.xml:/etc/ices2/ices-playlist.xml
      - ./nginx/hls:/songs
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
  proxy-network:
    external: true