services:
  node:
    image: node:23.6.1-alpine3.20
    container_name: node
    working_dir: /app
    volumes:
      - ./telegram-bot:/app
      - ./downloads:/app/downloads
    command: ["node", "server.js"]
    ports:
      - "5000:5000"
    networks:
      - app_network
  web:
    image: nginx:latest
    container_name: web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
