services:
  node:
    image: node:23.6.1-alpine3.20
    container_name: node
    working_dir: /app
    volumes:
      - ./telegram-bot:/app
    command: ["node", "server.js"]
    ports:
      - "5000:5000"
    networks:
      - app_network
  web:
    image: nginx:latest
    container_name: web
    working_dir: /usr/share/nginx/html
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/hls:/usr/share/nginx/html/hls
      - ./telegram-bot/downloads:/usr/share/nginx/html/downloads
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
